name: Daily Paper Translation

on:
  workflow_run:
    workflows: ["Daily Paper Download"]
    types:
      - completed
  workflow_dispatch:  # 允许手动触发
    inputs:
      start_date:
        description: '开始日期 (YYYY-MM-DD格式)'
        required: false
        type: string
      end_date:
        description: '结束日期 (YYYY-MM-DD格式)'
        required: false
        type: string
      single_date:
        description: '单个日期 (YYYY-MM-DD格式)'
        required: false
        type: string

jobs:
  translate-papers:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list  # 显示安装的包版本
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
    - name: Check environment
      run: |
        python -c "import openai; print(f'OpenAI version: {openai.__version__}')"
        python -c "import sys; print(f'Python version: {sys.version}')"
        
    - name: Check if papers exist
      id: check_papers
      run: |
        DATE="${{ github.event.inputs.single_date }}"
        if [[ -z "$DATE" ]]; then
          DATE="${{ steps.date.outputs.date }}"
        fi
        if [[ -d "Paper_metadata_download" ]] && [[ -f "Paper_metadata_download/$DATE.json" ]]; then
          echo "has_papers=true" >> $GITHUB_OUTPUT
        else
          echo "has_papers=false" >> $GITHUB_OUTPUT
          echo "No papers found for date $DATE, skipping translation"
        fi
        
    - name: Translate papers
      if: steps.check_papers.outputs.has_papers == 'true'
      env:
        INTERNLM_API_KEY: ${{ secrets.INTERNLM_API_KEY }}
      run: |
        if [[ -n "${{ github.event.inputs.start_date }}" && -n "${{ github.event.inputs.end_date }}" ]]; then
          python -X dev translate_papers.py --start_date "${{ github.event.inputs.start_date }}" --end_date "${{ github.event.inputs.end_date }}" --api_key "$INTERNLM_API_KEY"
        elif [[ -n "${{ github.event.inputs.single_date }}" ]]; then
          python -X dev translate_papers.py --date "${{ github.event.inputs.single_date }}" --api_key "$INTERNLM_API_KEY"
        else
          python -X dev translate_papers.py --date "${{ steps.date.outputs.date }}" --api_key "$INTERNLM_API_KEY"
        fi
        
    - name: Commit and push if changed
      if: steps.check_papers.outputs.has_papers == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Translated_papers/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Add translations $(date +'%Y-%m-%d')" && git push) 