name: Daily Paper Download

on:
  schedule:
    - cron: '0 1 * * *'  # 每天北京时间 9:00 运行
  workflow_dispatch:  # 允许手动触发
    inputs:
      start_date:
        description: '开始日期 (YYYY-MM-DD格式)'
        required: false
        type: string
      end_date:
        description: '结束日期 (YYYY-MM-DD格式)'
        required: false
        type: string
      single_date:
        description: '单个日期 (YYYY-MM-DD格式)'
        required: false
        type: string

jobs:
  download-papers:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download papers
      run: |
        if [[ -n "${{ github.event.inputs.start_date }}" && -n "${{ github.event.inputs.end_date }}" ]]; then
          python download_papers.py --start_date "${{ github.event.inputs.start_date }}" --end_date "${{ github.event.inputs.end_date }}"
        elif [[ -n "${{ github.event.inputs.single_date }}" ]]; then
          python download_papers.py --date "${{ github.event.inputs.single_date }}"
        else
          python download_papers.py
        fi
        
    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Paper_metadata_download/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update papers $(date +'%Y-%m-%d')" && git push) 