name: Daily Paper Translation

on:
  workflow_dispatch:
    inputs:
      date:
        description: '指定日期 (YYYY-MM-DD)'
        required: false
        type: string
      start_date:
        description: '开始日期 (YYYY-MM-DD)'
        required: false
        type: string
      end_date:
        description: '结束日期 (YYYY-MM-DD)'
        required: false
        type: string
  schedule:
    - cron: '0 7 * * *'  # UTC 7:00 (Beijing 15:00)

jobs:
  translate:
    runs-on: ubuntu-latest
    
    env:
      MASTER_KEY: ${{ secrets.MASTER_KEY }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Encrypt API key and translate papers
      run: |
        python -c "
        from utils import APIKeyManager
        import os
        
        # 加密 API key
        key_manager = APIKeyManager(os.environ['MASTER_KEY'])
        encrypted_key = key_manager.encrypt_api_key(os.environ['INTERNLM_API_KEY'])
        
        # 将加密后的 key 写入临时文件
        with open('.key_temp', 'w') as f:
            f.write(encrypted_key)
        "
        
        # 构建命令行参数
        CMD="python translate_papers.py --api_key $(cat .key_temp)"
        if [[ -n "${{ github.event.inputs.date }}" ]]; then
          CMD="$CMD --date ${{ github.event.inputs.date }}"
        elif [[ -n "${{ github.event.inputs.start_date }}" && -n "${{ github.event.inputs.end_date }}" ]]; then
          CMD="$CMD --start_date ${{ github.event.inputs.start_date }} --end_date ${{ github.event.inputs.end_date }}"
        fi
        
        # 执行翻译
        eval $CMD
        
        # 清理临时文件
        rm .key_temp
      env:
        INTERNLM_API_KEY: ${{ secrets.INTERNLM_API_KEY }}
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Translated_papers/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update translated papers" && git push) 