name: Daily Paper Translation

on:
  workflow_run:
    workflows: ["Daily Paper Download"]
    types:
      - completed
  workflow_dispatch:  # 允许手动触发

jobs:
  translate-papers:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list  # 显示安装的包版本
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
    - name: Check environment
      run: |
        python -c "import openai; print(f'OpenAI version: {openai.__version__}')"
        python -c "import sys; print(f'Python version: {sys.version}')"
        
    - name: Translate papers
      env:
        INTERNLM_API_KEY: ${{ secrets.INTERNLM_API_KEY }}
      run: |
        python -X dev translate_papers.py --date ${{ steps.date.outputs.date }} --api_key "$INTERNLM_API_KEY"
        
    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Translated_papers/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Add translations $(date +'%Y-%m-%d')" && git push) 